import { PrismaClient, Role, ActivityLevel, RiskLevel } from "@prisma/client";
import bcrypt from "bcryptjs";

const prisma = new PrismaClient();

const rwandanFoods = [
  // ─── GRAINS & STARCHES ──────────────────────────────────────────
  {
    id: "1",
    name: "White rice, boiled",
    nameKin: "Umuceli w'umweru",
    category: "starchy grain",
    glycemicIndex: 73,
    glycemicLoad: 23,
    caloriesPer100g: 130,
    carbsPer100g: 28,
    proteinPer100g: 2.7,
    fatPer100g: 0.3,
    isLocal: false,
  },
  {
    id: "2",
    name: "Brown rice, boiled",
    nameKin: "Umuceri w’ikigina utetse mu mazi ",
    category: "starchy grain",
    glycemicIndex: 68,
    glycemicLoad: 21,
    caloriesPer100g: 112,
    carbsPer100g: 23,
    proteinPer100g: 2.6,
    fatPer100g: 0.9,
    isLocal: false,
  },
  {
    id: "3",
    name: "Millet porridge",
    nameKin: "Igikoma cy'uburo",
    category: "starchy grain",
    glycemicIndex: 67,
    glycemicLoad: 14,
    caloriesPer100g: 70,
    carbsPer100g: 15,
    proteinPer100g: 2.1,
    fatPer100g: 0.8,
    isLocal: true,
  },
  {
    id: "4",
    name: "Sweet potato, boiled",
    nameKin: "Ibijumba",
    category: "starchy root",
    glycemicIndex: 63,
    glycemicLoad: 11,
    caloriesPer100g: 86,
    carbsPer100g: 20,
    proteinPer100g: 1.6,
    fatPer100g: 0.1,
    isLocal: true,
  },
  {
    id: "5",
    name: "Cassava, boiled",
    nameKin: "imyumbati yatogosheje",
    category: "starchy root",
    glycemicIndex: 55,
    glycemicLoad: 12,
    caloriesPer100g: 112,
    carbsPer100g: 27,
    proteinPer100g: 1.4,
    fatPer100g: 0.3,
    isLocal: true,
  },
  {
    id: "6",
    name: "Irish potato, boiled",
    nameKin: "Ibirayi bitogosheje",
    category: "starchy root",
    glycemicIndex: 78,
    glycemicLoad: 19,
    caloriesPer100g: 87,
    carbsPer100g: 20,
    proteinPer100g: 2.0,
    fatPer100g: 0.1,
    isLocal: true,
  },
  {
    id: "7",
    name: "Plantain, boiled",
    nameKin: "Agatogo k'ibitoki",
    category: "starchy fruit",
    glycemicIndex: 55,
    glycemicLoad: 12,
    caloriesPer100g: 122,
    carbsPer100g: 32,
    proteinPer100g: 1.3,
    fatPer100g: 0.4,
    isLocal: true,
  },
  {
    id: "8",
    name: "Plantain, fried",
    nameKin: "Imizuzu",
    category: "starchy fruit",
    glycemicIndex: 65,
    glycemicLoad: 16,
    caloriesPer100g: 180,
    carbsPer100g: 38,
    proteinPer100g: 1.2,
    fatPer100g: 3.5,
    isLocal: true,
  },
  {
    id: "9",
    name: "Ugali (maize flour)",
    nameKin: "Ubugali",
    category: "starchy grain",
    glycemicIndex: 70,
    glycemicLoad: 18,
    caloriesPer100g: 120,
    carbsPer100g: 26,
    proteinPer100g: 2.5,
    fatPer100g: 0.8,
    isLocal: true,
  },
  {
    id: "10",
    name: "Cassava‑maize paste",
    nameKin: "Umutsima",
    category: "starchy grain",
    glycemicIndex: 65,
    glycemicLoad: 16,
    caloriesPer100g: 115,
    carbsPer100g: 25,
    proteinPer100g: 2.2,
    fatPer100g: 0.6,
    isLocal: true,
  },
  {
    id: "11",
    name: "White wheat bread",
    nameKin: "Umugati w’ingano",
    category: "bread",
    glycemicIndex: 75,
    glycemicLoad: 9,
    caloriesPer100g: 265,
    carbsPer100g: 49,
    proteinPer100g: 9.4,
    fatPer100g: 3.2,
    isLocal: false,
  },
  {
    id: "12",
    name: "Whole wheat bread",
    nameKin: "Umugati w’ingano yuzuye",
    category: "bread",
    glycemicIndex: 74,
    glycemicLoad: 9,
    caloriesPer100g: 247,
    carbsPer100g: 41,
    proteinPer100g: 13.0,
    fatPer100g: 3.2,
    isLocal: false,
  },
  {
    id: "13",
    name: "Corn tortilla",
    nameKin: "Tortilla y’umusema",
    category: "bread",
    glycemicIndex: 46,
    glycemicLoad: 8,
    caloriesPer100g: 218,
    carbsPer100g: 41,
    proteinPer100g: 7.0,
    fatPer100g: 4.0,
    isLocal: false,
  },
  {
    id: "14",
    name: "Chapati",
    nameKin: "Chapati",
    category: "bread",
    glycemicIndex: 52,
    glycemicLoad: 10,
    caloriesPer100g: 275,
    carbsPer100g: 45,
    proteinPer100g: 9.0,
    fatPer100g: 7.0,
    isLocal: false,
  },
  {
    id: "15",
    name: "Oatmeal, cooked",
    nameKin: "igikoma cy'oats",
    category: "grain",
    glycemicIndex: 55,
    glycemicLoad: 8,
    caloriesPer100g: 68,
    carbsPer100g: 12,
    proteinPer100g: 2.4,
    fatPer100g: 1.4,
    isLocal: false,
  },
  {
    id: "16",
    name: "Barley, boiled",
    nameKin: "Ibararizi",
    category: "grain",
    glycemicIndex: 28,
    glycemicLoad: 5,
    caloriesPer100g: 125,
    carbsPer100g: 27,
    proteinPer100g: 2.3,
    fatPer100g: 0.5,
    isLocal: false,
  },
  {
    id: "17",
    name: "Sweet corn, boiled",
    nameKin: "Imbuto",
    category: "grain",
    glycemicIndex: 52,
    glycemicLoad: 15,
    caloriesPer100g: 96,
    carbsPer100g: 21,
    proteinPer100g: 3.3,
    fatPer100g: 1.2,
    isLocal: false,
  },
  {
    id: "18",
    name: "Lentils, cooked",
    nameKin: "Indengu zisindishijwe",
    category: "legume",
    glycemicIndex: 32,
    glycemicLoad: 5,
    caloriesPer100g: 116,
    carbsPer100g: 20,
    proteinPer100g: 9.0,
    fatPer100g: 0.4,
    isLocal: false,
  },
  {
    id: "19",
    name: "Red beans, cooked",
    nameKin: "Ibiharage",
    category: "legume",
    glycemicIndex: 29,
    glycemicLoad: 5,
    caloriesPer100g: 127,
    carbsPer100g: 22,
    proteinPer100g: 8.7,
    fatPer100g: 0.5,
    isLocal: true,
  },
  {
    id: "20",
    name: "Black beans, cooked",
    nameKin: "Ibishyimbo by’umukara",
    category: "legume",
    glycemicIndex: 30,
    glycemicLoad: 5,
    caloriesPer100g: 132,
    carbsPer100g: 23,
    proteinPer100g: 8.9,
    fatPer100g: 0.5,
    isLocal: false,
  },
  {
    id: "21",
    name: "Chickpeas, cooked",
    nameKin: "Ibisi mimpari",
    category: "legume",
    glycemicIndex: 28,
    glycemicLoad: 5,
    caloriesPer100g: 164,
    carbsPer100g: 27,
    proteinPer100g: 8.9,
    fatPer100g: 2.6,
    isLocal: false,
  },
  {
    id: "22",
    name: "Green peas, boiled",
    nameKin: "Ingororoma",
    category: "vegetable",
    glycemicIndex: 39,
    glycemicLoad: 4,
    caloriesPer100g: 81,
    carbsPer100g: 14,
    proteinPer100g: 5.4,
    fatPer100g: 0.4,
    isLocal: false,
  },
  {
    id: "23",
    name: "Kidney beans, cooked",
    nameKin: "Ibisi indi",
    category: "legume",
    glycemicIndex: 24,
    glycemicLoad: 4,
    caloriesPer100g: 127,
    carbsPer100g: 22,
    proteinPer100g: 8.2,
    fatPer100g: 0.5,
    isLocal: false,
  },
  {
    id: "24",
    name: "Mung beans, cooked",
    nameKin: "Ibisi mung",
    category: "legume",
    glycemicIndex: 27,
    glycemicLoad: 4,
    caloriesPer100g: 105,
    carbsPer100g: 19,
    proteinPer100g: 7.0,
    fatPer100g: 0.4,
    isLocal: false,
  },
  {
    id: "25",
    name: "Soybeans, cooked",
    nameKin: "Isoya isindishijwe",
    category: "legume",
    glycemicIndex: 15,
    glycemicLoad: 2,
    caloriesPer100g: 173,
    carbsPer100g: 10,
    proteinPer100g: 16.6,
    fatPer100g: 9.0,
    isLocal: false,
  },
  {
    id: "26",
    name: "Tofu",
    nameKin: "Tofu",
    category: "legume",
    glycemicIndex: 15,
    glycemicLoad: 2,
    caloriesPer100g: 76,
    carbsPer100g: 1.9,
    proteinPer100g: 8.1,
    fatPer100g: 4.2,
    isLocal: false,
  },
  {
    id: "27",
    name: "Milk, whole",
    nameKin: "Amata mashya",
    category: "dairy",
    glycemicIndex: 39,
    glycemicLoad: 4,
    caloriesPer100g: 64,
    carbsPer100g: 4.8,
    proteinPer100g: 3.2,
    fatPer100g: 3.3,
    isLocal: false,
  },
  {
    id: "28",
    name: "Milk, skim",
    nameKin: "Amata yijimye",
    category: "dairy",
    glycemicIndex: 37,
    glycemicLoad: 3,
    caloriesPer100g: 35,
    carbsPer100g: 5.0,
    proteinPer100g: 3.4,
    fatPer100g: 0.1,
    isLocal: false,
  },
  {
    id: "29",
    name: "Yogurt, plain",
    nameKin: "Yogurt idafite sukari",
    category: "dairy",
    glycemicIndex: 37,
    glycemicLoad: 5,
    caloriesPer100g: 59,
    carbsPer100g: 4.7,
    proteinPer100g: 3.5,
    fatPer100g: 3.3,
    isLocal: false,
  },
  {
    id: "30",
    name: "Cheese, cheddar",
    nameKin: "Furoma",
    category: "dairy",
    glycemicIndex: 35,
    glycemicLoad: 2,
    caloriesPer100g: 402,
    carbsPer100g: 1.3,
    proteinPer100g: 25.0,
    fatPer100g: 33.0,
    isLocal: false,
  },
  {
    id: "31",
    name: "Eggs, boiled",
    nameKin: "Amagi asindishijwe",
    category: "egg",
    glycemicIndex: 50,
    glycemicLoad: 1,
    caloriesPer100g: 155,
    carbsPer100g: 1.1,
    proteinPer100g: 12.6,
    fatPer100g: 10.6,
    isLocal: false,
  },
  {
    id: "32",
    name: "Chicken, breast, grilled",
    nameKin: "Inyama y’inkoko",
    category: "meat",
    glycemicIndex: 0,
    glycemicLoad: 0,
    caloriesPer100g: 165,
    carbsPer100g: 0.0,
    proteinPer100g: 31.0,
    fatPer100g: 3.6,
    isLocal: false,
  },
  {
    id: "33",
    name: "Beef, lean, grilled",
    nameKin: "Inyama y’inka",
    category: "meat",
    glycemicIndex: 0,
    glycemicLoad: 0,
    caloriesPer100g: 250,
    carbsPer100g: 0.0,
    proteinPer100g: 26.0,
    fatPer100g: 15.0,
    isLocal: false,
  },
  {
    id: "34",
    name: "Goat meat, grilled",
    nameKin: "Inyama y’ihene",
    category: "meat",
    glycemicIndex: 0,
    glycemicLoad: 0,
    caloriesPer100g: 180,
    carbsPer100g: 0.0,
    proteinPer100g: 27.0,
    fatPer100g: 8.0,
    isLocal: true,
  },
  {
    id: "35",
    name: "Pork, fried",
    nameKin: "Akabenz",
    category: "meat",
    glycemicIndex: 0,
    glycemicLoad: 0,
    caloriesPer100g: 300,
    carbsPer100g: 0.0,
    proteinPer100g: 26.0,
    fatPer100g: 20.0,
    isLocal: true,
  },
  {
    id: "36",
    name: "Fish, tilapia, grilled",
    nameKin: "Icyongoro",
    category: "fish",
    glycemicIndex: 0,
    glycemicLoad: 0,
    caloriesPer100g: 118,
    carbsPer100g: 0.0,
    proteinPer100g: 26.0,
    fatPer100g: 1.7,
    isLocal: true,
  },
  {
    id: "37",
    name: "Fish, smoked",
    nameKin: "Icyongoro kigira",
    category: "fish",
    glycemicIndex: 0,
    glycemicLoad: 0,
    caloriesPer100g: 140,
    carbsPer100g: 0.0,
    proteinPer100g: 28.0,
    fatPer100g: 3.0,
    isLocal: true,
  },
  {
    id: "38",
    name: "Sardines, canned",
    nameKin: "Satidini",
    category: "fish",
    glycemicIndex: 0,
    glycemicLoad: 0,
    caloriesPer100g: 208,
    carbsPer100g: 0.0,
    proteinPer100g: 24.6,
    fatPer100g: 11.5,
    isLocal: false,
  },
  {
    id: "39",
    name: "Apple, raw",
    nameKin: "Icyanya",
    category: "fruit",
    glycemicIndex: 36,
    glycemicLoad: 4,
    caloriesPer100g: 52,
    carbsPer100g: 14,
    proteinPer100g: 0.3,
    fatPer100g: 0.2,
    isLocal: false,
  },
  {
    id: "40",
    name: "Orange, raw",
    nameKin: "Imburajuba",
    category: "fruit",
    glycemicIndex: 43,
    glycemicLoad: 5,
    caloriesPer100g: 47,
    carbsPer100g: 12,
    proteinPer100g: 0.9,
    fatPer100g: 0.1,
    isLocal: false,
  },
  {
    id: "41",
    name: "Banana, raw",
    nameKin: "Imineke izeze",
    category: "fruit",
    glycemicIndex: 51,
    glycemicLoad: 12,
    caloriesPer100g: 89,
    carbsPer100g: 23,
    proteinPer100g: 1.1,
    fatPer100g: 0.3,
    isLocal: false,
  },
  {
    id: "42",
    name: "Mango, raw",
    nameKin: "Umwembe",
    category: "fruit",
    glycemicIndex: 51,
    glycemicLoad: 6,
    caloriesPer100g: 60,
    carbsPer100g: 15,
    proteinPer100g: 0.8,
    fatPer100g: 0.4,
    isLocal: false,
  },
  {
    id: "43",
    name: "Papaya",
    nameKin: "Ipapayi",
    category: "fruit",
    glycemicIndex: 60,
    glycemicLoad: 7,
    caloriesPer100g: 43,
    carbsPer100g: 11,
    proteinPer100g: 0.5,
    fatPer100g: 0.3,
    isLocal: false,
  },
  {
    id: "44",
    name: "Watermelon, raw",
    nameKin: "Meli",
    category: "fruit",
    glycemicIndex: 76,
    glycemicLoad: 3,
    caloriesPer100g: 30,
    carbsPer100g: 8,
    proteinPer100g: 0.6,
    fatPer100g: 0.2,
    isLocal: false,
  },
  {
    id: "45",
    name: "Pineapple",
    nameKin: "Inanasi",
    category: "fruit",
    glycemicIndex: 59,
    glycemicLoad: 7,
    caloriesPer100g: 50,
    carbsPer100g: 13,
    proteinPer100g: 0.5,
    fatPer100g: 0.1,
    isLocal: false,
  },
  {
    id: "46",
    name: "Grapes",
    nameKin: "Icyagine",
    category: "fruit",
    glycemicIndex: 59,
    glycemicLoad: 10,
    caloriesPer100g: 67,
    carbsPer100g: 18,
    proteinPer100g: 0.7,
    fatPer100g: 0.2,
    isLocal: false,
  },
  {
    id: "47",
    name: "Peach, canned",
    nameKin: "Pishi",
    category: "fruit",
    glycemicIndex: 43,
    glycemicLoad: 8,
    caloriesPer100g: 60,
    carbsPer100g: 15,
    proteinPer100g: 0.8,
    fatPer100g: 0.1,
    isLocal: false,
  },
  {
    id: "48",
    name: "Dates, raw",
    nameKin: "Date",
    category: "fruit",
    glycemicIndex: 42,
    glycemicLoad: 14,
    caloriesPer100g: 277,
    carbsPer100g: 75,
    proteinPer100g: 1.8,
    fatPer100g: 0.2,
    isLocal: false,
  },
  {
    id: "49",
    name: "Avocado",
    nameKin: "Avoka",
    category: "fruit",
    glycemicIndex: 10,
    glycemicLoad: 1,
    caloriesPer100g: 160,
    carbsPer100g: 9,
    proteinPer100g: 2.0,
    fatPer100g: 15.0,
    isLocal: false,
  },
  {
    id: "50",
    name: "Cucumber",
    nameKin: "Inzira",
    category: "vegetable",
    glycemicIndex: 15,
    glycemicLoad: 1,
    caloriesPer100g: 15,
    carbsPer100g: 4,
    proteinPer100g: 0.7,
    fatPer100g: 0.1,
    isLocal: false,
  },
  {
    id: "51",
    name: "Carrot, raw",
    nameKin: "Karoti",
    category: "vegetable",
    glycemicIndex: 39,
    glycemicLoad: 3,
    caloriesPer100g: 41,
    carbsPer100g: 10,
    proteinPer100g: 0.9,
    fatPer100g: 0.2,
    isLocal: false,
  },
  {
    id: "52",
    name: "Tomato, raw",
    nameKin: "Inyanya",
    category: "vegetable",
    glycemicIndex: 38,
    glycemicLoad: 3,
    caloriesPer100g: 18,
    carbsPer100g: 3.9,
    proteinPer100g: 0.9,
    fatPer100g: 0.2,
    isLocal: false,
  },
  {
    id: "53",
    name: "Spinach, raw",
    nameKin: "Umusugi",
    category: "vegetable",
    glycemicIndex: 15,
    glycemicLoad: 1,
    caloriesPer100g: 23,
    carbsPer100g: 3.6,
    proteinPer100g: 2.9,
    fatPer100g: 0.4,
    isLocal: false,
  },
  {
    id: "54",
    name: "Cabbage, raw",
    nameKin: "Ishu",
    category: "vegetable",
    glycemicIndex: 15,
    glycemicLoad: 2,
    caloriesPer100g: 25,
    carbsPer100g: 5.8,
    proteinPer100g: 1.3,
    fatPer100g: 0.1,
    isLocal: false,
  },
  {
    id: "55",
    name: "Onion, raw",
    nameKin: "Igitunguru",
    category: "vegetable",
    glycemicIndex: 10,
    glycemicLoad: 2,
    caloriesPer100g: 40,
    carbsPer100g: 9.3,
    proteinPer100g: 1.1,
    fatPer100g: 0.1,
    isLocal: false,
  },
  {
    id: "56",
    name: "Garlic",
    nameKin: "Ubaha",
    category: "vegetable",
    glycemicIndex: 10,
    glycemicLoad: 1,
    caloriesPer100g: 149,
    carbsPer100g: 33,
    proteinPer100g: 6.4,
    fatPer100g: 0.5,
    isLocal: false,
  },
  {
    id: "57",
    name: "Eggplant",
    nameKin: "Intoryi",
    category: "vegetable",
    glycemicIndex: 15,
    glycemicLoad: 3,
    caloriesPer100g: 25,
    carbsPer100g: 6,
    proteinPer100g: 1.0,
    fatPer100g: 0.2,
    isLocal: false,
  },
  {
    id: "58",
    name: "Green pepper",
    nameKin: "Urusenda rw’icyatsi",
    category: "vegetable",
    glycemicIndex: 15,
    glycemicLoad: 2,
    caloriesPer100g: 20,
    carbsPer100g: 4.6,
    proteinPer100g: 0.9,
    fatPer100g: 0.2,
    isLocal: false,
  },
  {
    id: "59",
    name: "Pumpkin, boiled",
    nameKin: "Igihaza",
    category: "vegetable",
    glycemicIndex: 64,
    glycemicLoad: 7,
    caloriesPer100g: 26,
    carbsPer100g: 6,
    proteinPer100g: 1.0,
    fatPer100g: 0.1,
    isLocal: false,
  },
  {
    id: "60",
    name: "Taro, boiled",
    nameKin: "Taro",
    category: "vegetable",
    glycemicIndex: 53,
    glycemicLoad: 11,
    caloriesPer100g: 112,
    carbsPer100g: 26,
    proteinPer100g: 1.4,
    fatPer100g: 0.2,
    isLocal: false,
  },
  {
    id: "61",
    name: "Cassava leaves, cooked",
    nameKin: "Isombe",
    category: "leafy vegetable",
    glycemicIndex: 15,
    glycemicLoad: 2,
    caloriesPer100g: 35,
    carbsPer100g: 4.1,
    proteinPer100g: 2.5,
    fatPer100g: 0.4,
    isLocal: true,
  },
  {
    id: "62",
    name: "Baobab fruit pulp",
    nameKin: "Umubare",
    category: "fruit",
    glycemicIndex: 30,
    glycemicLoad: 6,
    caloriesPer100g: 268,
    carbsPer100g: 62,
    proteinPer100g: 3.0,
    fatPer100g: 0.6,
    isLocal: true,
  },
  {
    id: "63",
    name: "Groundnuts (peanuts), raw",
    nameKin: "Ubunyobwa",
    category: "legume",
    glycemicIndex: 14,
    glycemicLoad: 4,
    caloriesPer100g: 567,
    carbsPer100g: 16,
    proteinPer100g: 26.0,
    fatPer100g: 49.0,
    isLocal: true,
  },
  {
    id: "64",
    name: "Peanut butter",
    nameKin: "Ibinyobwa butter",
    category: "legume",
    glycemicIndex: 14,
    glycemicLoad: 8,
    caloriesPer100g: 594,
    carbsPer100g: 21,
    proteinPer100g: 24.0,
    fatPer100g: 51.0,
    isLocal: true,
  },
  {
    id: "65",
    name: "Sesame seeds",
    nameKin: "Semuze",
    category: "seed",
    glycemicIndex: 35,
    glycemicLoad: 6,
    caloriesPer100g: 573,
    carbsPer100g: 23,
    proteinPer100g: 20.0,
    fatPer100g: 50.0,
    isLocal: false,
  },
  {
    id: "66",
    name: "Sunflower seeds",
    nameKin: "Sunflower",
    category: "seed",
    glycemicIndex: 35,
    glycemicLoad: 5,
    caloriesPer100g: 584,
    carbsPer100g: 20,
    proteinPer100g: 21.0,
    fatPer100g: 51.0,
    isLocal: false,
  },
  {
    id: "67",
    name: "Maize kernels, raw",
    nameKin: "Umusema",
    category: "grain",
    glycemicIndex: 52,
    glycemicLoad: 11,
    caloriesPer100g: 365,
    carbsPer100g: 74,
    proteinPer100g: 9.4,
    fatPer100g: 4.7,
    isLocal: true,
  },
  {
    id: "68",
    name: "Maize flour, white",
    nameKin: "Umusema flour",
    category: "grain",
    glycemicIndex: 65,
    glycemicLoad: 14,
    caloriesPer100g: 350,
    carbsPer100g: 75,
    proteinPer100g: 8.5,
    fatPer100g: 4.0,
    isLocal: true,
  },
  {
    id: "69",
    name: "Millet flour",
    nameKin: "Umusema mpaka",
    category: "grain",
    glycemicIndex: 65,
    glycemicLoad: 14,
    caloriesPer100g: 355,
    carbsPer100g: 78,
    proteinPer100g: 11.0,
    fatPer100g: 3.5,
    isLocal: true,
  },
  {
    id: "70",
    name: "Sorghum flour",
    nameKin: "Umusema soja",
    category: "grain",
    glycemicIndex: 65,
    glycemicLoad: 13,
    caloriesPer100g: 340,
    carbsPer100g: 75,
    proteinPer100g: 10.0,
    fatPer100g: 3.3,
    isLocal: true,
  },
  {
    id: "71",
    name: "Rice flour",
    nameKin: "Umuceri flour",
    category: "grain",
    glycemicIndex: 70,
    glycemicLoad: 15,
    caloriesPer100g: 360,
    carbsPer100g: 80,
    proteinPer100g: 7.0,
    fatPer100g: 0.8,
    isLocal: false,
  },
  {
    id: "72",
    name: "Banana flour",
    nameKin: "Ibivyo flour",
    category: "grain",
    glycemicIndex: 45,
    glycemicLoad: 9,
    caloriesPer100g: 330,
    carbsPer100g: 78,
    proteinPer100g: 3.5,
    fatPer100g: 0.5,
    isLocal: false,
  },
  {
    id: "73",
    name: "Cassava flour",
    nameKin: "Manihoti flour",
    category: "grain",
    glycemicIndex: 65,
    glycemicLoad: 14,
    caloriesPer100g: 340,
    carbsPer100g: 80,
    proteinPer100g: 1.5,
    fatPer100g: 0.5,
    isLocal: true,
  },
  {
    id: "74",
    name: "Whole wheat flour",
    nameKin: "Ifu y’ingano yuzuye",
    category: "grain",
    glycemicIndex: 65,
    glycemicLoad: 13,
    caloriesPer100g: 340,
    carbsPer100g: 72,
    proteinPer100g: 13.0,
    fatPer100g: 2.5,
    isLocal: false,
  },
  {
    id: "75",
    name: "White wheat flour",
    nameKin: "Ifu y’ingano yera",
    category: "grain",
    glycemicIndex: 65,
    glycemicLoad: 14,
    caloriesPer100g: 364,
    carbsPer100g: 76,
    proteinPer100g: 10.3,
    fatPer100g: 1.0,
    isLocal: false,
  },
  {
    id: "76",
    name: "Coca‑Cola",
    nameKin: "Coca‑Cola",
    category: "beverage",
    glycemicIndex: 63,
    glycemicLoad: 13,
    caloriesPer100g: 42,
    carbsPer100g: 10.6,
    proteinPer100g: 0.0,
    fatPer100g: 0.0,
    isLocal: false,
  },
  {
    id: "77",
    name: "Orange juice, unsweetened",
    nameKin: "Umutobe w’imicungarariko",
    category: "beverage",
    glycemicIndex: 50,
    glycemicLoad: 12,
    caloriesPer100g: 45,
    carbsPer100g: 11.0,
    proteinPer100g: 0.7,
    fatPer100g: 0.2,
    isLocal: false,
  },
  {
    id: "78",
    name: "Apple juice, unsweetened",
    nameKin: "Umutobe w’icyanya",
    category: "beverage",
    glycemicIndex: 41,
    glycemicLoad: 10,
    caloriesPer100g: 46,
    carbsPer100g: 11.0,
    proteinPer100g: 0.3,
    fatPer100g: 0.1,
    isLocal: false,
  },
  {
    id: "79",
    name: "Beer, regular",
    nameKin: "Urubega",
    category: "beverage",
    glycemicIndex: 66,
    glycemicLoad: 11,
    caloriesPer100g: 43,
    carbsPer100g: 3.6,
    proteinPer100g: 0.5,
    fatPer100g: 0.0,
    isLocal: false,
  },
  {
    id: "80",
    name: "Palm wine",
    nameKin: "Ubugari bw’imikindo",
    category: "beverage",
    glycemicIndex: 45,
    glycemicLoad: 9,
    caloriesPer100g: 50,
    carbsPer100g: 12.0,
    proteinPer100g: 0.5,
    fatPer100g: 0.0,
    isLocal: false,
  },
  {
    id: "81",
    name: "Coconut water",
    nameKin: "Amazi y’umukokoti",
    category: "beverage",
    glycemicIndex: 45,
    glycemicLoad: 6,
    caloriesPer100g: 19,
    carbsPer100g: 3.7,
    proteinPer100g: 0.7,
    fatPer100g: 0.2,
    isLocal: false,
  },
  {
    id: "82",
    name: "Sugar, white",
    nameKin: "Isukari yera",
    category: "sweetener",
    glycemicIndex: 65,
    glycemicLoad: 65,
    caloriesPer100g: 387,
    carbsPer100g: 99.9,
    proteinPer100g: 0.0,
    fatPer100g: 0.0,
    isLocal: false,
  },
  {
    id: "83",
    name: "Sugar, brown",
    nameKin: "Isukari yijimye",
    category: "sweetener",
    glycemicIndex: 65,
    glycemicLoad: 65,
    caloriesPer100g: 380,
    carbsPer100g: 98.0,
    proteinPer100g: 0.0,
    fatPer100g: 0.0,
    isLocal: false,
  },

  // ─── ADDITIONS FROM YOUR rwandanFoods ARRAY (not in CSV) ──────────
  {
    name: "Cassava Porridge",
    nameKin: "Ubugari",
    category: "grain",
    glycemicIndex: 94,
    glycemicLoad: 37,
    caloriesPer100g: 345,
    carbsPer100g: 83,
    proteinPer100g: 1,
    fatPer100g: 0,
    isLocal: true,
  },
  {
    name: "Sorghum Porridge",
    nameKin: "Umutsima w’inkomati",
    category: "grain",
    glycemicIndex: 55,
    glycemicLoad: 17,
    caloriesPer100g: 71,
    carbsPer100g: 15,
    proteinPer100g: 2,
    fatPer100g: 0,
    isLocal: true,
  },
  {
    name: "Wheat Flour Porridge",
    nameKin: "Ubuyi bw’ingano",
    category: "grain",
    glycemicIndex: 74,
    glycemicLoad: 26,
    caloriesPer100g: 360,
    carbsPer100g: 76,
    proteinPer100g: 10,
    fatPer100g: 1,
    isLocal: false,
  },
  {
    name: "Yam (boiled)",
    nameKin: "Igisafuriya",
    category: "vegetable",
    glycemicIndex: 37,
    glycemicLoad: 8,
    caloriesPer100g: 118,
    carbsPer100g: 28,
    proteinPer100g: 2,
    fatPer100g: 0,
    isLocal: true,
  },
  {
    name: "Passion Fruit",
    nameKin: "Maracuja",
    category: "fruit",
    glycemicIndex: 30,
    glycemicLoad: 3,
    caloriesPer100g: 97,
    carbsPer100g: 23,
    proteinPer100g: 2,
    fatPer100g: 1,
    isLocal: true,
  },
  {
    name: "Guava",
    nameKin: "Ipera",
    category: "fruit",
    glycemicIndex: 31,
    glycemicLoad: 3,
    caloriesPer100g: 68,
    carbsPer100g: 14,
    proteinPer100g: 3,
    fatPer100g: 1,
    isLocal: true,
  },
  {
    name: "Cowpeas (boiled)",
    nameKin: "Inyakura zisindishijwe",
    category: "legume",
    glycemicIndex: 33,
    glycemicLoad: 6,
    caloriesPer100g: 116,
    carbsPer100g: 21,
    proteinPer100g: 8,
    fatPer100g: 1,
    isLocal: true,
  },
  {
    name: "Nile Perch (grilled)",
    nameKin: "Inkamba ishyushwe",
    category: "protein",
    glycemicIndex: 0,
    glycemicLoad: 0,
    caloriesPer100g: 111,
    carbsPer100g: 0,
    proteinPer100g: 23,
    fatPer100g: 2,
    isLocal: true,
  },
  {
    name: "Fermented Milk (Ikivuguto)",
    nameKin: "Ikivuguto",
    category: "dairy",
    glycemicIndex: 27,
    glycemicLoad: 3,
    caloriesPer100g: 40,
    carbsPer100g: 3,
    proteinPer100g: 3,
    fatPer100g: 1,
    isLocal: true,
  },
  {
    name: "Mandazi / Fried Dough",
    nameKin: "Mandazi",
    category: "bread",
    glycemicIndex: 76,
    glycemicLoad: 30,
    caloriesPer100g: 360,
    carbsPer100g: 52,
    proteinPer100g: 7,
    fatPer100g: 14,
    isLocal: true,
  },
  {
    name: "Samosa (baked)",
    nameKin: "Samosa",
    category: "bread",
    glycemicIndex: 55,
    glycemicLoad: 18,
    caloriesPer100g: 262,
    carbsPer100g: 33,
    proteinPer100g: 6,
    fatPer100g: 12,
    isLocal: false,
  },
  {
    name: "Ugali with Beans",
    nameKin: "Ubugali n’ibiharage",
    category: "grain",
    glycemicIndex: 52,
    glycemicLoad: 22,
    caloriesPer100g: 280,
    carbsPer100g: 55,
    proteinPer100g: 10,
    fatPer100g: 1,
    isLocal: true,
  },
  {
    name: "Rice with Beans",
    nameKin: "Umuceri n’ibiharage",
    category: "grain",
    glycemicIndex: 56,
    glycemicLoad: 21,
    caloriesPer100g: 180,
    carbsPer100g: 37,
    proteinPer100g: 7,
    fatPer100g: 1,
    isLocal: true,
  },
  {
    name: "Isombe with Cassava",
    nameKin: "Isombe n’imihumbati",
    category: "vegetable",
    glycemicIndex: 38,
    glycemicLoad: 10,
    caloriesPer100g: 120,
    carbsPer100g: 25,
    proteinPer100g: 4,
    fatPer100g: 0,
    isLocal: true,
  },
  {
    name: "Tea with Sugar",
    nameKin: "Icyayi gifite sukari",
    category: "drink",
    glycemicIndex: 65,
    glycemicLoad: 13,
    caloriesPer100g: 30,
    carbsPer100g: 8,
    proteinPer100g: 0,
    fatPer100g: 0,
    isLocal: true,
  },
  {
    name: "Tea without Sugar",
    nameKin: "Icyayi nta sukari",
    category: "drink",
    glycemicIndex: 0,
    glycemicLoad: 0,
    caloriesPer100g: 1,
    carbsPer100g: 0,
    proteinPer100g: 0,
    fatPer100g: 0,
    isLocal: true,
  },
  {
    name: "Fresh Fruit Juice (unsweetened)",
    nameKin: "Umusemburo w’imbuto udafite sukari",
    category: "drink",
    glycemicIndex: 45,
    glycemicLoad: 6,
    caloriesPer100g: 45,
    carbsPer100g: 11,
    proteinPer100g: 0,
    fatPer100g: 0,
    isLocal: true,
  },
  {
    name: "Sorghum Beer (Ikigage)",
    nameKin: "Ikigage",
    category: "drink",
    glycemicIndex: 66,
    glycemicLoad: 10,
    caloriesPer100g: 43,
    carbsPer100g: 5,
    proteinPer100g: 0,
    fatPer100g: 0,
    isLocal: true,
  },
  {
    name: "Water",
    nameKin: "Amazi",
    category: "drink",
    glycemicIndex: 0,
    glycemicLoad: 0,
    caloriesPer100g: 0,
    carbsPer100g: 0,
    proteinPer100g: 0,
    fatPer100g: 0,
    isLocal: true,
  },
];

async function main() {
  console.log("🌱 Seeding database...");

  // Clean existing data (safe for development only)
  await prisma.dietRecommendation.deleteMany();
  await prisma.prediction.deleteMany();
  await prisma.message.deleteMany();
  await prisma.medication.deleteMany();
  await prisma.healthRecord.deleteMany();
  await prisma.user.deleteMany();

  const passwordHash = await bcrypt.hash("Test@1234", 12);

  // ── Create 1 Doctor ───────────────────────────────────────────────
  const doctor1 = await prisma.user.create({
    data: {
      fullName: "Dr. Amina Uwase",
      email: "doctor@aidiatrack.rw",
      passwordHash,
      role: Role.DOCTOR,
      phone: "+250788000001",
      gender: "Female",
      language: "rw",
    },
  });

  // ── Create 2 Patients ──────────────────────────────────────────────
  const patient1 = await prisma.user.create({
    data: {
      fullName: "Marie Mukamana",
      email: "patient1@aidiatrack.rw",
      passwordHash,
      role: Role.PATIENT,
      phone: "+250788100001",
      gender: "Female",
      dateOfBirth: new Date("1978-03-15"),
      doctorId: doctor1.id,
      language: "rw",
    },
  });

  const patient2 = await prisma.user.create({
    data: {
      fullName: "Emmanuel Habimana",
      email: "patient2@aidiatrack.rw",
      passwordHash,
      role: Role.PATIENT,
      phone: "+250788100002",
      gender: "Male",
      dateOfBirth: new Date("1965-07-22"),
      doctorId: doctor1.id,
      language: "en",
    },
  });

  // ── Health Records for Patient 1 ──────────────────────────────────
  const glucoseReadings = [145, 162, 138, 175, 120];
  const createdHealthRecords: Array<{ id: number }> = [];
  for (let i = 0; i < glucoseReadings.length; i++) {
    const date = new Date();
    date.setDate(date.getDate() - (4 - i));
    const healthRecord = await prisma.healthRecord.create({
      data: {
        patientId: patient1.id,
        bloodGlucose: glucoseReadings[i],
        weightKg: 68.5,
        bmi: 25.4,
        mealDesc:
          i % 2 === 0 ? "Ugali with beans and vegetables" : "Rice with isombe",
        calories: i % 2 === 0 ? 520 : 480,
        activityLevel: ActivityLevel.LOW,
        insulinDose: 0,
        notes: "Feeling okay",
        recordedAt: date,
      },
    });
    createdHealthRecords.push({ id: healthRecord.id });
  }

  // ── Medications for Patient 1 ─────────────────────────────────────
  await prisma.medication.createMany({
    data: [
      {
        patientId: patient1.id,
        drugName: "Metformin",
        dosage: "500mg",
        frequency: "twice daily",
        reminderTimes: ["08:00", "20:00"],
        isActive: true,
        prescribedBy: doctor1.id,
      },
      {
        patientId: patient1.id,
        drugName: "Glipizide",
        dosage: "5mg",
        frequency: "once daily",
        reminderTimes: ["09:00"],
        isActive: true,
        prescribedBy: doctor1.id,
      },
      {
        patientId: patient1.id,
        drugName: "Lisinopril",
        dosage: "10mg",
        frequency: "once daily",
        reminderTimes: ["07:30"],
        isActive: true,
        prescribedBy: doctor1.id,
      },
    ],
  });

  // ── Sample Prediction for Patient 1 ──────────────────────────────
  await prisma.prediction.create({
    data: {
      patientId: patient1.id,
      predictedGlucose: 168.5,
      predictionHours: 2,
      riskLevel: RiskLevel.MEDIUM,
      riskFactors: { high_carb_meal: true, low_activity: true },
      confidence: 0.82,
      modelVersion: "1.0.0-placeholder",
    },
  });

  // ── Sample Chat Messages ──────────────────────────────────────────
  await prisma.message.createMany({
    data: [
      {
        senderId: patient1.id,
        receiverId: doctor1.id,
        content:
          "Good morning doctor, my sugar was 175 this morning after breakfast.",
        isRead: true,
      },
      {
        senderId: doctor1.id,
        receiverId: patient1.id,
        content:
          "Thank you Marie. Please reduce your carbohydrate intake at breakfast.",
        isRead: true,
      },
      {
        senderId: patient1.id,
        receiverId: doctor1.id,
        content: "I also felt a little tired after lunch.",
        isRead: false,
      },
      {
        senderId: doctor1.id,
        receiverId: patient1.id,
        content: "Try a short walk after meals and keep your hydration up.",
        isRead: false,
      },
      {
        senderId: patient1.id,
        receiverId: doctor1.id,
        content: "Understood, I will log my next reading this evening.",
        isRead: false,
      },
    ],
  });

  // ── Sample Diet Recommendation for Patient 1 ─────────────────────
  await prisma.dietRecommendation.create({
    data: {
      patientId: patient1.id,
      recommendationText:
        "Focus on balanced meals with beans, greens, avocado, and controlled portions of whole grains.",
      foodsToEat: ["beans", "spinach", "avocado", "whole grains"],
      foodsToAvoid: [
        "sugary drinks",
        "fried snacks",
        "large white bread portions",
      ],
      basedOnRecordId: createdHealthRecords[createdHealthRecords.length - 1].id,
    },
  });

  // -- Rwandan Food Database Seed -------------------------------------
  for (const food of rwandanFoods) {
    await prisma.foodItem.upsert({
      where: { name: food.name },
      update: {
        nameKin: food.nameKin,
        category: food.category,
        glycemicIndex: food.glycemicIndex,
        glycemicLoad: food.glycemicLoad,
        caloriesPer100g: food.caloriesPer100g,
        carbsPer100g: food.carbsPer100g,
        proteinPer100g: food.proteinPer100g,
        fatPer100g: food.fatPer100g,
        isLocal: food.isLocal,
      },
      create: {
        name: food.name,
        nameKin: food.nameKin,
        category: food.category,
        glycemicIndex: food.glycemicIndex,
        glycemicLoad: food.glycemicLoad,
        caloriesPer100g: food.caloriesPer100g,
        carbsPer100g: food.carbsPer100g,
        proteinPer100g: food.proteinPer100g,
        fatPer100g: food.fatPer100g,
        isLocal: food.isLocal,
      },
    });
  }

  console.log(`✅ ${rwandanFoods.length} food items seeded`);
  console.log("✅ Seed complete!");

  console.log(
    `   Users    : ${doctor1.fullName}, ${patient1.fullName}, ${patient2.fullName}`,
  );
  console.log(`   Password : Test@1234  (all accounts)`);
}

main()
  .catch((e) => {
    console.error("❌ Seed failed:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
